package org.americanair.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-15T12:08:05.473-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.americanair.org/demo/", name = "AmericanAirSystemServices")
@XmlSeeAlso({ObjectFactory.class})
public interface AmericanAirSystemServices {

    @WebMethod
    @RequestWrapper(localName = "cancelarReserva", targetNamespace = "http://www.americanair.org/demo/", className = "org.americanair.demo.CancelarReserva")
    @ResponseWrapper(localName = "cancelarReservaResponse", targetNamespace = "http://www.americanair.org/demo/", className = "org.americanair.demo.CancelarReservaResponse")
    public void cancelarReserva(
        @WebParam(name = "idReserva", targetNamespace = "")
        java.lang.String idReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigo", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> codigo,
        @WebParam(mode = WebParam.Mode.OUT, name = "mensaje", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerReserva", targetNamespace = "http://www.americanair.org/demo/", className = "org.americanair.demo.ObtenerReserva")
    @ResponseWrapper(localName = "obtenerReservaResponse", targetNamespace = "http://www.americanair.org/demo/", className = "org.americanair.demo.ObtenerReservaResponse")
    public void obtenerReserva(
        @WebParam(mode = WebParam.Mode.INOUT, name = "idReserva", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> idReserva,
        @WebParam(mode = WebParam.Mode.OUT, name = "pasajeros", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<org.americanair.demo.Persona>> pasajeros,
        @WebParam(mode = WebParam.Mode.OUT, name = "vuelo", targetNamespace = "")
        javax.xml.ws.Holder<Vuelo> vuelo
    );

    @WebMethod
    @RequestWrapper(localName = "realizarReserva", targetNamespace = "http://www.americanair.org/demo/", className = "org.americanair.demo.RealizarReserva")
    @ResponseWrapper(localName = "realizarReservaResponse", targetNamespace = "http://www.americanair.org/demo/", className = "org.americanair.demo.RealizarReservaResponse")
    public void realizarReserva(
        @WebParam(name = "idReserva", targetNamespace = "")
        java.lang.String idReserva,
        @WebParam(name = "pasajeros", targetNamespace = "")
        java.util.List<org.americanair.demo.Persona> pasajeros,
        @WebParam(name = "vuelo", targetNamespace = "")
        org.americanair.demo.Vuelo vuelo,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigo", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> codigo,
        @WebParam(mode = WebParam.Mode.OUT, name = "mensaje", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado
    );
}
